spring:
  jmx:
    enabled: false
  cache:
    ehcache:
      config: classpath:ehcache.xml
  datasource:
    url: jdbc:mysql://192.168.1.67:3306/englishAssistantDb?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: mysql
    password: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
        hibernate.cache.use_second_level_cache: true
        hibernate.cache.use_query_cache: true
        hibernate.cache.region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        hibernate.javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
  devtools:
    restart:
      enabled: true
server:
  port: 8080